### ISSUE TITLE
Copy the code to tcp/linux/src/bbr.c 

### ISSUE THREAD

**Issue by SoonyangZhang** [maesoser/ns2_bbr#1]
Sorry，did not get the point of this instruction. Copy which code to tcp/linux/src/bbr.c？the original bbr code implement in linux?

**Comment by maesoser** [comment]
The instructions are outdated, I will fix that. As you correctly figured out, they refer to the original bbr code, but we end up porting the code to ns-2 instead. I must warn you it is on pre-pre-pre alpha and it is not currently working, contributions are welcome.

What you've to do is to replace tcp.h by the modified header file, for instance:

`cp tcp.h ns-allinone-2.35/ns-2.35/tcp/tcp.h`

And later copy the .cc code into the same tcp folder.

`cp tcp-bbr.cc ns-allinone-2.35/ns-2.35/tcp/tcp-bbr.cc`

**Comment by SoonyangZhang** [comment]
ok, When I compile the code.there are errors.  The fucntions in win_minmax should be imported. And the size of icsk_ca_priv to 88bytes. And others?

**Comment by maesoser** [comment]
Sorry,I think I've not explained it clear enough. This code does not use the original bbr code included on linux, so it does not use neither `linux/win_minmax.h` nor `icsk_ca_priv` structure so you do not have to copy anything inside the tcp/linux/src folder.

I've updated the readme, take a look at it and inside the Makefile and let me know if you've more doubts!
